// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZznV2_qBhgxxNHZlb6ALxxDDFmRW3LwA',
    appId: '1:1027194434560:web:facea854ee762ebd29d4e5',
    messagingSenderId: '1027194434560',
    projectId: 'cena-firebase-mad3',
    authDomain: 'cena-firebase-mad3.firebaseapp.com',
    storageBucket: 'cena-firebase-mad3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDolxxjmDBLMzlLUdRcXLTakOIWdNs-1YE',
    appId: '1:1027194434560:android:f1dcd371a742f98b29d4e5',
    messagingSenderId: '1027194434560',
    projectId: 'cena-firebase-mad3',
    storageBucket: 'cena-firebase-mad3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy3iSn07Ye2j9XkkjNv_9aARj_PbJ1eDc',
    appId: '1:1027194434560:ios:edee9623c5569ae629d4e5',
    messagingSenderId: '1027194434560',
    projectId: 'cena-firebase-mad3',
    storageBucket: 'cena-firebase-mad3.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );
}
